name = "esp-sound-meter"
main = "src/index.ts"
compatibility_date = "2022-10-21"
compatibility_flags = [ "nodejs_compat" ]

analytics_engine_datasets = [
    { binding = "SOUNDMETER", dataset = "SoundMeter" },
    { binding = "SOUNDMETER_E1", dataset = "SoundMeter_E1" },
    { binding = "SOUNDMETER_E2", dataset = "SoundMeter_E2" },
    { binding = "SOUNDMETER_E3", dataset = "SoundMeter_E3" },
    { binding = "SOUNDMETER_E4", dataset = "SoundMeter_E4" },
    { binding = "SOUNDMETER_E5", dataset = "SoundMeter_E5" },
    { binding = "SOUNDMETER_E6", dataset = "SoundMeter_E6" },
    { binding = "SOUNDMETER_E7", dataset = "SoundMeter_E7" }
]

# secrets:
# use "wrangler secret put HOME_ASSISTANT_BEARER_TOKEN" to set a bearer token.

[vars]
ACCOUNT_ID = "d5ad95b51b1a7b1d707058ca362cc00d"

# Schedule cron triggers:
[triggers]
crons = [ '* * * * *' ] # - At every minute
